-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 17:29:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LibraryManagementDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LibraryManagementDB` ;

-- -----------------------------------------------------
-- Schema LibraryManagementDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibraryManagementDB` DEFAULT CHARACTER SET utf8 ;
USE `LibraryManagementDB` ;

-- -----------------------------------------------------
-- Table `Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Language` ;

CREATE TABLE IF NOT EXISTS `Language` (
  `language_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Region` ;

CREATE TABLE IF NOT EXISTS `Region` (
  `region_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `language_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`region_id`),
  INDEX `fk_region_language_idx` (`language_fk` ASC) VISIBLE,
  CONSTRAINT `fk_region_language`
    FOREIGN KEY (`language_fk`)
    REFERENCES `Language` (`language_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Library` ;

CREATE TABLE IF NOT EXISTS `Library` (
  `library_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `region_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`library_id`),
  INDEX `fk_library_region_idx` (`region_fk` ASC) VISIBLE,
  CONSTRAINT `fk_library_region`
    FOREIGN KEY (`region_fk`)
    REFERENCES `Region` (`region_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `School` ;

CREATE TABLE IF NOT EXISTS `School` (
  `school_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `library_fk` INT UNSIGNED NULL,
  `region_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`school_id`),
  INDEX `fk_school_library_idx` (`library_fk` ASC) VISIBLE,
  INDEX `fk_school_region_idx` (`region_fk` ASC) VISIBLE,
  CONSTRAINT `fk_school_library`
    FOREIGN KEY (`library_fk`)
    REFERENCES `Library` (`library_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_school_region`
    FOREIGN KEY (`region_fk`)
    REFERENCES `Region` (`region_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Person` ;

CREATE TABLE IF NOT EXISTS `Person` (
  `person_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `DOB` DATE NULL,
  `region_fk` INT UNSIGNED NULL,
  `parent_id` INT UNSIGNED NULL,
  PRIMARY KEY (`person_id`),
  INDEX `fk_person_region_idx` (`region_fk` ASC) VISIBLE,
  INDEX `fk_person_person_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_region`
    FOREIGN KEY (`region_fk`)
    REFERENCES `Region` (`region_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_person_person`
    FOREIGN KEY (`parent_id`)
    REFERENCES `Person` (`person_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Membership` ;

CREATE TABLE IF NOT EXISTS `Membership` (
  `member_id` INT ZEROFILL UNSIGNED NOT NULL,
  `person_fk` INT UNSIGNED NOT NULL,
  `library_fk` INT UNSIGNED NOT NULL,
  `pin` INT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `fk_membership_library_idx` (`library_fk` ASC) VISIBLE,
  INDEX `fk_membership_person_idx` (`person_fk` ASC) VISIBLE,
  CONSTRAINT `fk_membership_library`
    FOREIGN KEY (`library_fk`)
    REFERENCES `Library` (`library_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_membership_person`
    FOREIGN KEY (`person_fk`)
    REFERENCES `Person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `student_id` INT UNSIGNED ZEROFILL NOT NULL,
  `member_fk` INT UNSIGNED ZEROFILL NULL,
  `person_fk` INT UNSIGNED NOT NULL,
  `school_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_student_school_idx` (`school_fk` ASC) VISIBLE,
  INDEX `fk_student_person_idx` (`person_fk` ASC) VISIBLE,
  CONSTRAINT `fk_student_school`
    FOREIGN KEY (`school_fk`)
    REFERENCES `School` (`school_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_student_person`
    FOREIGN KEY (`person_fk`)
    REFERENCES `Person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_student_member`
    FOREIGN KEY (`member_fk`)
    REFERENCES `Membership` (`member_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff` ;

CREATE TABLE IF NOT EXISTS `Staff` (
  `staff_id` INT UNSIGNED NOT NULL,
  `library_fk` INT UNSIGNED NULL,
  `is_librarian` TINYINT NULL,
  `member_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`staff_id`, `member_fk`),
  INDEX `fk_staff_library_idx` (`library_fk` ASC) VISIBLE,
  INDEX `fk_staff_member_idx` (`member_fk` ASC) VISIBLE,
  CONSTRAINT `fk_staff_library`
    FOREIGN KEY (`library_fk`)
    REFERENCES `Library` (`library_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_staff_member`
    FOREIGN KEY (`member_fk`)
    REFERENCES `Membership` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Work` ;

CREATE TABLE IF NOT EXISTS `Work` (
  `work_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`work_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Instance` ;

CREATE TABLE IF NOT EXISTS `Instance` (
  `instance_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `date` DATETIME NULL,
  `work_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`instance_id`),
  INDEX `fk_instance_work_idx` (`work_fk` ASC) VISIBLE,
  CONSTRAINT `fk_instance_work`
    FOREIGN KEY (`work_fk`)
    REFERENCES `Work` (`work_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vendor` ;

CREATE TABLE IF NOT EXISTS `Vendor` (
  `vendor_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `region_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`vendor_id`),
  INDEX `fk_vendor_region_idx` (`region_fk` ASC) VISIBLE,
  CONSTRAINT `fk_vendor_region`
    FOREIGN KEY (`region_fk`)
    REFERENCES `Region` (`region_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Item` ;

CREATE TABLE IF NOT EXISTS `Item` (
  `item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `instance_fk` INT UNSIGNED NULL,
  `supplier_fk` INT UNSIGNED NULL,
  `catalogger_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_item_instance_idx` (`instance_fk` ASC) VISIBLE,
  INDEX `fk_item_vendor_idx` (`supplier_fk` ASC) VISIBLE,
  INDEX `fk_item_staff_idx` (`catalogger_fk` ASC) VISIBLE,
  CONSTRAINT `fk_item_instance`
    FOREIGN KEY (`instance_fk`)
    REFERENCES `Instance` (`instance_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_vendor`
    FOREIGN KEY (`supplier_fk`)
    REFERENCES `Vendor` (`vendor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_staff`
    FOREIGN KEY (`catalogger_fk`)
    REFERENCES `Staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subject` ;

CREATE TABLE IF NOT EXISTS `Subject` (
  `subject_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `overarching_subject_id` INT UNSIGNED NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `fk_subject_subject_idx` (`overarching_subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_subject_subject`
    FOREIGN KEY (`overarching_subject_id`)
    REFERENCES `Subject` (`subject_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Agent` ;

CREATE TABLE IF NOT EXISTS `Agent` (
  `agent_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `organization_id` INT UNSIGNED NULL,
  `LC_PCN` VARCHAR(45) NULL,
  PRIMARY KEY (`agent_id`),
  INDEX `fk_agent_agent_idx` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `fk_agent_agent`
    FOREIGN KEY (`organization_id`)
    REFERENCES `Agent` (`agent_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Event` ;

CREATE TABLE IF NOT EXISTS `Event` (
  `event_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `date` DATETIME NULL,
  `region_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`event_id`),
  INDEX `fk_event_region_idx` (`region_fk` ASC) VISIBLE,
  CONSTRAINT `fk_event_region`
    FOREIGN KEY (`region_fk`)
    REFERENCES `Region` (`region_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Format`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Format` ;

CREATE TABLE IF NOT EXISTS `Format` (
  `format_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `language_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`format_id`),
  INDEX `fk_format_language_idx` (`language_fk` ASC) VISIBLE,
  CONSTRAINT `fk_format_language`
    FOREIGN KEY (`language_fk`)
    REFERENCES `Language` (`language_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Floor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Floor` ;

CREATE TABLE IF NOT EXISTS `Floor` (
  `floor_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `library_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`floor_id`),
  INDEX `fk_floor_library_idx` (`library_fk` ASC) VISIBLE,
  CONSTRAINT `fk_floor_library`
    FOREIGN KEY (`library_fk`)
    REFERENCES `Library` (`library_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Room` ;

CREATE TABLE IF NOT EXISTS `Room` (
  `room_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `floor_fk` INT UNSIGNED NULL,
  `capacity` INT UNSIGNED NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_room_floor_idx` (`floor_fk` ASC) VISIBLE,
  CONSTRAINT `fk_room_floor`
    FOREIGN KEY (`floor_fk`)
    REFERENCES `Floor` (`floor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookstack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookstack` ;

CREATE TABLE IF NOT EXISTS `Bookstack` (
  `bookstack_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_fk` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`bookstack_id`, `room_fk`),
  CONSTRAINT `fk_bookstack_room`
    FOREIGN KEY (`room_fk`)
    REFERENCES `Room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shelf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shelf` ;

CREATE TABLE IF NOT EXISTS `Shelf` (
  `shelf_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bookstack_fk` INT UNSIGNED NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`shelf_id`),
  INDEX `fk_shelf_bookstack_idx` (`bookstack_fk` ASC) VISIBLE,
  CONSTRAINT `fk_shelf_bookstack`
    FOREIGN KEY (`bookstack_fk`)
    REFERENCES `Bookstack` (`bookstack_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryEvent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryEvent` ;

CREATE TABLE IF NOT EXISTS `LibraryEvent` (
  `lib_event_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NULL,
  PRIMARY KEY (`lib_event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Form` ;

CREATE TABLE IF NOT EXISTS `Form` (
  `form_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `creator_fk` INT UNSIGNED NULL,
  `form_location` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`form_id`),
  INDEX `fk_form_staff_idx` (`creator_fk` ASC) VISIBLE,
  CONSTRAINT `fk_form_staff`
    FOREIGN KEY (`creator_fk`)
    REFERENCES `Staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CompleteForm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CompleteForm` ;

CREATE TABLE IF NOT EXISTS `CompleteForm` (
  `processing_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_fk` INT UNSIGNED NOT NULL,
  `form_fk` INT UNSIGNED NULL,
  `processor_fk` INT UNSIGNED NULL,
  `is_valid` TINYINT NOT NULL DEFAULT 0,
  `form_location` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`processing_id`),
  INDEX `fk_completeform_form_idx` (`form_fk` ASC) VISIBLE,
  INDEX `fk_completeform_person_idx` (`person_fk` ASC) VISIBLE,
  INDEX `fk_completeform_staff_idx` (`processor_fk` ASC) VISIBLE,
  CONSTRAINT `fk_completeform_form`
    FOREIGN KEY (`form_fk`)
    REFERENCES `Form` (`form_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_completeform_person`
    FOREIGN KEY (`person_fk`)
    REFERENCES `Person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_completeform_staff`
    FOREIGN KEY (`processor_fk`)
    REFERENCES `Staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrganizedEvent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OrganizedEvent` ;

CREATE TABLE IF NOT EXISTS `OrganizedEvent` (
  `org_event_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organizer_fk` INT UNSIGNED NULL,
  `lib_event_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`org_event_id`, `lib_event_fk`),
  INDEX `fk_orgevent_staff_idx` (`organizer_fk` ASC) VISIBLE,
  INDEX `fk_orgevent_libevent_idx` (`lib_event_fk` ASC) VISIBLE,
  CONSTRAINT `fk_orgevent_staff`
    FOREIGN KEY (`organizer_fk`)
    REFERENCES `Staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orgevent_libevent`
    FOREIGN KEY (`lib_event_fk`)
    REFERENCES `LibraryEvent` (`lib_event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Attendance` ;

CREATE TABLE IF NOT EXISTS `Attendance` (
  `attendance_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `attendant_fk` INT UNSIGNED NOT NULL,
  `org_event_fk` INT UNSIGNED NOT NULL,
  INDEX `fk_attendance_orgevent_idx` (`org_event_fk` ASC) VISIBLE,
  INDEX `fk_attendance_person_idx` (`attendant_fk` ASC) VISIBLE,
  PRIMARY KEY (`attendance_id`),
  CONSTRAINT `fk_attendance_orgevent`
    FOREIGN KEY (`org_event_fk`)
    REFERENCES `OrganizedEvent` (`org_event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attendance_person`
    FOREIGN KEY (`attendant_fk`)
    REFERENCES `Person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CalendarEvent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CalendarEvent` ;

CREATE TABLE IF NOT EXISTS `CalendarEvent` (
  `cal_event_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lib_event_fk` INT UNSIGNED NULL,
  `library_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`cal_event_id`),
  INDEX `fk_calevent_libevent_idx` (`lib_event_fk` ASC) VISIBLE,
  INDEX `fk_calevent_library_idx` (`library_fk` ASC) VISIBLE,
  CONSTRAINT `fk_calevent_libevent`
    FOREIGN KEY (`lib_event_fk`)
    REFERENCES `LibraryEvent` (`lib_event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_calevent_library`
    FOREIGN KEY (`library_fk`)
    REFERENCES `Library` (`library_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Equipment` ;

CREATE TABLE IF NOT EXISTS `Equipment` (
  `equipment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `library_fk` INT UNSIGNED NULL,
  `model` VARCHAR(45) NULL,
  `serial_num` VARCHAR(45) NULL,
  `supplier_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`equipment_id`),
  INDEX `fk_equipment_library_idx` (`library_fk` ASC) VISIBLE,
  INDEX `fk_equipment_vendor_idx` (`supplier_fk` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_library`
    FOREIGN KEY (`library_fk`)
    REFERENCES `Library` (`library_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_equipment_vendor`
    FOREIGN KEY (`supplier_fk`)
    REFERENCES `Vendor` (`vendor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EquipmentReservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EquipmentReservation` ;

CREATE TABLE IF NOT EXISTS `EquipmentReservation` (
  `e_reservation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `equipment_fk` INT UNSIGNED NOT NULL,
  `member_fk` INT ZEROFILL UNSIGNED NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  PRIMARY KEY (`e_reservation_id`),
  INDEX `fk_ereservation_equipment_idx` (`equipment_fk` ASC) VISIBLE,
  INDEX `fk_ereservation_member_idx` (`member_fk` ASC) VISIBLE,
  CONSTRAINT `fk_Ereservation_equipment`
    FOREIGN KEY (`equipment_fk`)
    REFERENCES `Equipment` (`equipment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ereservation_member`
    FOREIGN KEY (`member_fk`)
    REFERENCES `Membership` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PhysicalItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PhysicalItem` ;

CREATE TABLE IF NOT EXISTS `PhysicalItem` (
  `call_number` VARCHAR(45) NOT NULL,
  `item_fk` INT UNSIGNED NOT NULL,
  `shelf_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`call_number`, `item_fk`),
  INDEX `fk_physicalitem_shelf_idx` (`shelf_fk` ASC) VISIBLE,
  CONSTRAINT `fk_physicalitem_item`
    FOREIGN KEY (`item_fk`)
    REFERENCES `Item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_physicalitem_shelf`
    FOREIGN KEY (`shelf_fk`)
    REFERENCES `Shelf` (`shelf_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ItemReservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ItemReservation` ;

CREATE TABLE IF NOT EXISTS `ItemReservation` (
  `i_reservation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_fk` VARCHAR(45) NOT NULL,
  `member_fk` INT ZEROFILL UNSIGNED NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  PRIMARY KEY (`i_reservation_id`),
  INDEX `fk_ireservation_member_idx` (`member_fk` ASC) VISIBLE,
  INDEX `fk_ireservation_physicalitem_idx` (`item_fk` ASC) VISIBLE,
  CONSTRAINT `fk_Ireservation_physicalitem`
    FOREIGN KEY (`item_fk`)
    REFERENCES `PhysicalItem` (`call_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ireservation_member`
    FOREIGN KEY (`member_fk`)
    REFERENCES `Membership` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReservableRoom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ReservableRoom` ;

CREATE TABLE IF NOT EXISTS `ReservableRoom` (
  `reservable_room_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`reservable_room_id`, `room_fk`),
  CONSTRAINT `fk_reservableroom_room`
    FOREIGN KEY (`room_fk`)
    REFERENCES `Room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoomReservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RoomReservation` ;

CREATE TABLE IF NOT EXISTS `RoomReservation` (
  `r_reservation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_fk` INT UNSIGNED NOT NULL,
  `member_fk` INT ZEROFILL UNSIGNED NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  PRIMARY KEY (`r_reservation_id`),
  INDEX `fk_rreservation_member_idx` (`member_fk` ASC) VISIBLE,
  INDEX `fk_rreservation_room_idx` (`room_fk` ASC) VISIBLE,
  CONSTRAINT `fk_Rreservation_room`
    FOREIGN KEY (`room_fk`)
    REFERENCES `ReservableRoom` (`reservable_room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Rreservation_member`
    FOREIGN KEY (`member_fk`)
    REFERENCES `Membership` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Publisher` ;

CREATE TABLE IF NOT EXISTS `Publisher` (
  `publisher_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `region_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`publisher_id`),
  INDEX `fk_publisher_region_idx` (`region_fk` ASC) VISIBLE,
  CONSTRAINT `fk_publisher_region`
    FOREIGN KEY (`region_fk`)
    REFERENCES `Region` (`region_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media` ;

CREATE TABLE IF NOT EXISTS `Media` (
  `media_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `instance_fk` INT UNSIGNED NULL,
  `format_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`media_id`),
  INDEX `fk_media_format_idx` (`format_fk` ASC) VISIBLE,
  INDEX `fk_media_instance_idx` (`instance_fk` ASC) VISIBLE,
  CONSTRAINT `fk_media_format`
    FOREIGN KEY (`format_fk`)
    REFERENCES `Format` (`format_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_media_instance`
    FOREIGN KEY (`instance_fk`)
    REFERENCES `Instance` (`instance_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Issue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Issue` ;

CREATE TABLE IF NOT EXISTS `Issue` (
  `issue_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `publisher_fk` INT UNSIGNED NULL,
  `instance_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`issue_id`),
  INDEX `fk_issue_publisher_idx` (`publisher_fk` ASC) VISIBLE,
  INDEX `fk_issue_instance_idx` (`instance_fk` ASC) VISIBLE,
  CONSTRAINT `fk_issue_publisher`
    FOREIGN KEY (`publisher_fk`)
    REFERENCES `Publisher` (`publisher_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_issue_instance`
    FOREIGN KEY (`instance_fk`)
    REFERENCES `Instance` (`instance_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Discussion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Discussion` ;

CREATE TABLE IF NOT EXISTS `Discussion` (
  `discussion_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subject_fk` INT UNSIGNED NOT NULL,
  `work_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`discussion_id`),
  INDEX `fk_discussion_subject_idx` (`subject_fk` ASC) VISIBLE,
  INDEX `fk_discussion_work_idx` (`work_fk` ASC) VISIBLE,
  CONSTRAINT `fk_discussion_subject`
    FOREIGN KEY (`subject_fk`)
    REFERENCES `Subject` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_discussion_work`
    FOREIGN KEY (`work_fk`)
    REFERENCES `Work` (`work_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Description`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Description` ;

CREATE TABLE IF NOT EXISTS `Description` (
  `description_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `work_fk` INT UNSIGNED NOT NULL,
  `event_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`description_id`),
  INDEX `fk_description_event_idx` (`event_fk` ASC) VISIBLE,
  INDEX `fk_description_work_idx` (`work_fk` ASC) VISIBLE,
  CONSTRAINT `fk_description_event`
    FOREIGN KEY (`event_fk`)
    REFERENCES `Event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_description_work`
    FOREIGN KEY (`work_fk`)
    REFERENCES `Work` (`work_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contribution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contribution` ;

CREATE TABLE IF NOT EXISTS `Contribution` (
  `contribution_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `work_fk` INT UNSIGNED NOT NULL,
  `agent_fk` INT UNSIGNED NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`contribution_id`),
  INDEX `fk_contribution_agent_idx` (`agent_fk` ASC) VISIBLE,
  INDEX `fk_contribution_work_idx` (`work_fk` ASC) VISIBLE,
  CONSTRAINT `fk_contribution_agent`
    FOREIGN KEY (`agent_fk`)
    REFERENCES `Agent` (`agent_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contribution_work`
    FOREIGN KEY (`work_fk`)
    REFERENCES `Work` (`work_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkReference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkReference` ;

CREATE TABLE IF NOT EXISTS `WorkReference` (
  `w_reference_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `referencer_fk` INT UNSIGNED NOT NULL,
  `referenced_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`w_reference_id`),
  INDEX `fk_wReference_work_referencer_idx` (`referencer_fk` ASC) VISIBLE,
  INDEX `fk_wReference_work_referenced_idx` (`referenced_fk` ASC) VISIBLE,
  CONSTRAINT `fk_wReference_work_referencer`
    FOREIGN KEY (`referencer_fk`)
    REFERENCES `Work` (`work_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_wReference_work_referenced`
    FOREIGN KEY (`referenced_fk`)
    REFERENCES `Work` (`work_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstanceReference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InstanceReference` ;

CREATE TABLE IF NOT EXISTS `InstanceReference` (
  `i_reference_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `referencer_fk` INT UNSIGNED NOT NULL,
  `referenced_fk` INT UNSIGNED NULL,
  PRIMARY KEY (`i_reference_id`),
  INDEX `fk_instanceReference_instance_referencer_idx` (`referencer_fk` ASC) VISIBLE,
  INDEX `fk_instanceRefernce_instance_referenced_idx` (`referenced_fk` ASC) VISIBLE,
  CONSTRAINT `fk_iReference_instance_referencer`
    FOREIGN KEY (`referencer_fk`)
    REFERENCES `Instance` (`instance_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_iReference_instance_referenced`
    FOREIGN KEY (`referenced_fk`)
    REFERENCES `Instance` (`instance_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
